### ISSUE TITLE
HG8240 VS_AUTH_KEY Help

### ISSUE THREAD

**Issue by mauimauer** [Anime4000/RTL9601C1#13]
Hey there,

could you help me out for the correct VS_AUTH_KEY so I can set the correct ELAN MAC? Your help is very much appreciated:

VS_AUTH_KEY?
ELAN_MAC_ADDR: 80D4A5AB9700-10
HW_HWVER: 140DC601

Many thanks.

**Comment by kswong319** [comment]
VSAUTHKEYGEN.EXE 80:D4:A5:AB:97:00 140DC601
VS_AUTH_KEY = 8D6668143DCE7FE0D7178C4D7F933B1C

**Comment by kswong319** [comment]
> 
> 
> Hey there,
> 
> could you help me out for the correct VS_AUTH_KEY so I can set the correct ELAN MAC? Your help is very much appreciated:
> 
> VS_AUTH_KEY? ELAN_MAC_ADDR: 80D4A5AB9700-10 HW_HWVER: 140DC601
> 
> Many thanks.

VSAUTHKEYGEN.EXE 80:D4:A5:AB:97:00 140DC601
VS_AUTH_KEY = 8D6668143DCE7FE0D7178C4D7F933B1C

![2021-10-06 113923](https://user-images.githubusercontent.com/52724975/136137222-e5cd7593-457d-49fa-90e2-76eaac21000d.jpg)
