### ISSUE TITLE
auto reboot even with correct VS_AUTH_KEY

### ISSUE THREAD

**Issue by amaumene** [Anime4000/RTL9601C1#15]
Hi,

I have a V2801F stick. I have set the intel VS_AUTH_KEY (and matching ELAN_MAC_ADDR and HW_HWVER) found [here](https://github.com/Anime4000/RTL9601C1/blob/main/Docs/FLASH_GETSET_INFO.md) but I still need to do ```echo 3 > /proc/fiber_mode``` otherwise my stick will keep rebooting in loop.

I'm not too sure it's related but ```# cat /tmp/authinfo``` shows:
```auth success```

My firmware is version ```V1.9.0-201104 --  Wed Nov 4 09:41:21 CST 2020```

Any idea why? Thanks in advance.

**Comment by Anime4000** [comment]
Nice Cat XD

when did you buy V2801F? I heard there so many revision.

Have you save previous value `flash get` ? try put original value see if reboot still happen

**Comment by amaumene** [comment]
I bought it recently. I tried with the original values but I'm facing the same issue... :(

**Comment by Anime4000** [comment]
if your stick is ODI with Realtek, it not work mostly, the laser driver quite different, currently I testing it
