### ISSUE TITLE
AFM0002TIM

### ISSUE THREAD

**Issue by stich86** [Anime4000/RTL9601C1#7]
Hi guys,

i've the SFP on object (that is usitng RTL9601B) running firmware V1_7_8_181123.
Do you think is possible to cross-flash a more recent firmware?

I've also opened the stick, looks like there are two point marked R/T that should be UART may be, but i'm missing the power pads, should I use the SFP connector?

Thanks

**Comment by Anime4000** [comment]
some stick have disabled UART, or missing resistor, but you can read memory directly
