### ISSUE TITLE
How to Generate VS_AUTH _KEY? 

### ISSUE THREAD

**Issue by ToTheCLI** [Anime4000/RTL9601C1#8]
I can achieve O5 But no Internet connection I suspect I have to Clone Mac Address of Original Huawei ONT and HWVER So I need VS_AUTH_KEY to stop reboot when I change ELAN_MAC and HWVER Parameters.
HWVER:172D.A
MAC Address:70fd4581f942

Please help generate VS_AUTH_KEY.

**Comment by ToTheCLI** [comment]
I have V2801F xPON Stick.

**Comment by ToTheCLI** [comment]
Found Solution 
https://github.com/tonyfulls845/Hacking_RTL9601C1/raw/a04ed2c069d1b3314f92a5d16d24aac05260c5eb/V2801F/VsAuthKeyGen.exe

**Comment by Anime4000** [comment]
nice
