### ISSUE TITLE
Using V2801f in Ubiquiti UDM-Pro

### ISSUE THREAD

**Issue by maxifus** [Anime4000/RTL9601C1#9]
UDM-Pro is very picky with SPF and this is causing lots of modules to not to work with it.

V2801f can work with it given the correct settiings: https://community.ui.com/questions/UDM-PRO-GPON-SFP-CarlitoxxPro-CPGOS03-0490-v2-0/362172d4-8a5f-4bda-a841-4a34c075c57f?page=2

However, current firmware doesn't have set Transceiver Compliance Code (offset 0x03) according to  SFF-8472, with should be "\x00\x00\x00\x02\x00\x00\x00\x00" (1000Base-L (1000BASE-LX) - good)
![Captura de Pantalla 2021-08-24 a la(s) 19 16 58](https://user-images.githubusercontent.com/16501526/130993585-aeaa3620-f768-482e-a25d-77c672e735bb.png)

Does anyone know how to set it using i2c get/set ??
Tried but don't know how to use this commands:
```
Connected to 192.168.1.2.
Escape character is '^]'.
login: admin
Password: 


BusyBox v1.12.4 (2019-07-05 11:31:46 CST) built-in shell (ash)
Enter 'help' for a list of built-in commands.

# diag
RTK.0> i2c get "0x03" 
               ^Parse error
RTK.0> i2c get 0x03  
               ^Parse error
RTK.0>
```
Any help would be appreciated

**Comment by Anime4000** [comment]
currently I use EdgeRouter 12, replace my broken RB3011UiAS-RM.

during setup, I notice Ubiquiti using 192.168.1.1/24 as default LAN, however, V2801F also using same subnet, this is not good, either change IP Address on Ubiquiti or V2801F.

I decide to change Ubiquiti LAN Subnet to 192.168.88.1/24 (follow default RB3011UiAS-RM),
I add sfp an IP Address, 192.168.1.2, and add into NAT list, so I can access 192.168.1.1 from 192.168.88.1

Also, I use `V2801F_V1.9.0-201104.tar` on my TWCGPON657

So far EdgeRouter 12 detect correctly
![image](https://user-images.githubusercontent.com/1908715/131361270-ac5e2fff-447f-4f31-bce1-655e1b1e4675.png)
